version: 2.1
jobs:
  build-arm64:
    docker:
      - image: cimg/base:current
    resource_class: medium
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build and publish arm64 image
          command: |
            echo $CR_PAT | docker login ghcr.io -u sorbet-multiarch-bot --password-stdin
            PUBLISH=true ./build.sh
  build-amd64:
    docker:
      - image: cimg/base:current
    resource_class: arm.medium
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build and publish amd64 image
          command: |
            echo $CR_PAT | docker login ghcr.io -u sorbet-multiarch-bot --password-stdin
            PUBLISH=true ./build.sh
workflows:
  build:
    jobs:
      - build-arm64:
          filters:
            branches:
              only: main
      - build-amd64:
          filters:
            branches:
              only: main
